# directory of the dataset
dataset: '/home/martin/Pictures/datasets/kitti/data_odometry_gray/dataset/sequences/00/'

# whether write the pose to txt file or not
if_write_pose: true

# whether use rviz visualization or not
if_rviz: false